use crate::{My, space::DaType};

pub const NO_OF_SHIPS: usize = 33;

// warning
pub const SHIP_SUN: DaType = -2;
pub const SHIP_PLANET: DaType = -1;
pub const SHIP_MISSILE: DaType = 1;
pub const SHIP_CORIOLIS: DaType = 2;
pub const SHIP_ESCAPE_CAPSULE: DaType = 3;
pub const SHIP_ALLOY: DaType = 4;
pub const SHIP_CARGO: DaType = 5;
pub const SHIP_BOULDER: DaType = 6;
pub const SHIP_ASTEROID: DaType = 7;
pub const SHIP_ROCK: DaType = 8;
pub const SHIP_SHUTTLE: DaType = 9;
pub const SHIP_TRANSPORTER: DaType = 10;
pub const SHIP_COBRA3: DaType = 11;
pub const SHIP_PYTHON: DaType = 12;
pub const SHIP_BOA: DaType = 13;
pub const SHIP_ANACONDA: DaType = 14;
pub const SHIP_HERMIT: DaType = 15;
pub const SHIP_VIPER: DaType = 16;
pub const SHIP_SIDEWINDER: DaType = 17;
pub const SHIP_MAMBA: DaType = 18;
pub const SHIP_KRAIT: DaType = 19;
pub const SHIP_ADDER: DaType = 20;
pub const SHIP_GECKO: DaType = 21;
pub const SHIP_COBRA1: DaType = 22;
pub const SHIP_WORM: DaType = 23;
pub const SHIP_COBRA3_LONE: DaType = 24;
pub const SHIP_ASP2: DaType = 25;
pub const SHIP_PYTHON_LONE: DaType = 26;
pub const SHIP_FER_DE_LANCE: DaType = 27;
pub const SHIP_MORAY: DaType = 28;
pub const SHIP_THARGOID: DaType = 29;
pub const SHIP_THARGLET: DaType = 30;
pub const SHIP_CONSTRICTOR: DaType = 31;
pub const SHIP_COUGAR: DaType = 32;
pub const SHIP_DODEC: DaType = 33;
